<h1>Содержание<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Загрузка-данных" data-toc-modified-id="Загрузка-данных-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Загрузка данных</a></span><ul class="toc-item"><li><span><a href="#EDA" data-toc-modified-id="EDA-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>EDA</a></span></li><li><span><a href="#Разделение-данных-на-признаки-и-выборки:" data-toc-modified-id="Разделение-данных-на-признаки-и-выборки:-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Разделение данных на признаки и выборки:</a></span></li></ul></li><li><span><a href="#Умножение-матриц" data-toc-modified-id="Умножение-матриц-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Умножение матриц</a></span></li><li><span><a href="#Алгоритм-преобразования" data-toc-modified-id="Алгоритм-преобразования-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Алгоритм преобразования</a></span></li><li><span><a href="#Проверка-алгоритма" data-toc-modified-id="Проверка-алгоритма-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Проверка алгоритма</a></span></li><li><span><a href="#Вывод:" data-toc-modified-id="Вывод:-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Вывод:</a></span></li><li><span><a href="#Чек-лист-проверки" data-toc-modified-id="Чек-лист-проверки-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Чек-лист проверки</a></span></li></ul></div>

# Защита персональных данных клиентов

Вам нужно защитить данные клиентов страховой компании «Хоть потоп». Разработайте такой метод преобразования данных, чтобы по ним было сложно восстановить персональную информацию. Обоснуйте корректность его работы.

Нужно защитить данные, чтобы при преобразовании качество моделей машинного обучения не ухудшилось. Подбирать наилучшую модель не требуется.

## Загрузка данных

### EDA

In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.metrics import r2_score

from sklearn.linear_model import LinearRegression

In [2]:
try:
    data = pd.read_csv('/datasets/insurance.csv')
except:
    print('Путь неверный')

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Пол                5000 non-null   int64  
 1   Возраст            5000 non-null   float64
 2   Зарплата           5000 non-null   float64
 3   Члены семьи        5000 non-null   int64  
 4   Страховые выплаты  5000 non-null   int64  
dtypes: float64(2), int64(3)
memory usage: 195.4 KB


In [4]:
data.head()

Пол  Возраст  Зарплата  Члены семьи  Страховые выплаты
0    1     41.0   49600.0            1                  0
1    0     46.0   38000.0            1                  1
2    0     29.0   21000.0            0                  0
3    0     21.0   41700.0            2                  0
4    1     28.0   26100.0            0                  0

In [5]:
data.describe()

Пол      Возраст      Зарплата  Члены семьи  Страховые выплаты
count  5000.000000  5000.000000   5000.000000  5000.000000        5000.000000
mean      0.499000    30.952800  39916.360000     1.194200           0.148000
std       0.500049     8.440807   9900.083569     1.091387           0.463183
min       0.000000    18.000000   5300.000000     0.000000           0.000000
25%       0.000000    24.000000  33300.000000     0.000000           0.000000
50%       0.000000    30.000000  40200.000000     1.000000           0.000000
75%       1.000000    37.000000  46600.000000     2.000000           0.000000
max       1.000000    65.000000  79000.000000     6.000000           5.000000

In [6]:
data.corr()

Пол   Возраст  Зарплата  Члены семьи  \
Пол                1.000000  0.002074  0.014910    -0.008991   
Возраст            0.002074  1.000000 -0.019093    -0.006692   
Зарплата           0.014910 -0.019093  1.000000    -0.030296   
Члены семьи       -0.008991 -0.006692 -0.030296     1.000000   
Страховые выплаты  0.010140  0.651030 -0.014963    -0.036290   

                   Страховые выплаты  
Пол                         0.010140  
Возраст                     0.651030  
Зарплата                   -0.014963  
Члены семьи                -0.036290  
Страховые выплаты           1.000000

In [7]:
data.isna().sum()

Пол                  0
Возраст              0
Зарплата             0
Члены семьи          0
Страховые выплаты    0
dtype: int64

In [8]:
data.duplicated().sum()

153

In [9]:
data[data.duplicated()]

Пол  Возраст  Зарплата  Члены семьи  Страховые выплаты
281     1     39.0   48100.0            1                  0
488     1     24.0   32900.0            1                  0
513     0     31.0   37400.0            2                  0
718     1     22.0   32600.0            1                  0
785     0     20.0   35800.0            0                  0
...   ...      ...       ...          ...                ...
4793    1     24.0   37800.0            0                  0
4902    1     35.0   38700.0            1                  0
4935    1     19.0   32700.0            0                  0
4945    1     21.0   45800.0            0                  0
4965    0     22.0   40100.0            1                  0

[153 rows x 5 columns]

**Вывод:** в данных нет пропусков. Однако имеются выбросы и дупликаты. Тем не менее, это не мешает для выполнения задачи проекта.

### Разделение данных на признаки и выборки:

In [10]:
features = data.drop(['Страховые выплаты'],axis=1)
target = data['Страховые выплаты']

In [11]:
train_features, test_features, train_target, test_target = train_test_split(features,target, test_size=0.25, random_state=12345)

## Умножение матриц

В этом задании вы можете записывать формулы в *Jupyter Notebook.*

Чтобы записать формулу внутри текста, окружите её символами доллара \\$; если снаружи —  двойными символами \\$\\$. Эти формулы записываются на языке вёрстки *LaTeX.* 

Для примера мы записали формулы линейной регрессии. Можете их скопировать и отредактировать, чтобы решить задачу.

Работать в *LaTeX* необязательно.

Обозначения:

- $X$ — матрица признаков (нулевой столбец состоит из единиц)

- $y$ — вектор целевого признака

- $P$ — матрица, на которую умножаются признаки

- $w$ — вектор весов линейной регрессии (нулевой элемент равен сдвигу)

 
    
Знаем:    
    
$$
w = (X^T X)^{-1} X^T y
$$
 
    
Значит:
    
$$
w' = ((XP)^T XP)^{-1} (XP)^T y
$$
    
    
Вот так мы сделать не можем:    
    
$
((XР)^T(XР))^{-1} = (XP)^{-1}((XP)^T)^{-1}
$    


    
Потому что произведение

    
$
XP
$    

не квадратная матрица, следовательно
    
$    
(XP)^{-1}
$
    
и  
    
$
((XP)^{T})^{-1} 
$    
 
 и  
    
$
X^{-1} 
$ 

   
$$
w' = (P^T X^T X P)^{-1} (XP)^T y
$$
    

    
$$
w' = (P^T (X^T X) P)^{-1} P^T X^T y
$$    
    
    
$
P^T, (X^T X), P
$   
    
Используем правило:
    
    
$$(ABC)^{-1} = C^{-1}(AB)^{-1} = (BC)^{-1}A^{-1} = C^{-1}B^{-1}A^{-1}$$
    
    
    
следовательно раскрываем так:

    
$$
w' = P^{-1} (X^T X)^{-1} (P^T)^{-1} P^T X^T y
$$    

    
Так как 
    
$$
w = (X^T X)^{-1} X^T y
$$

то
    
$$
w' = P^{-1}w
$$    
    
И так как


$$    
a' = X\cdot P\cdot w'    
$$ 

то


$$    
a' = X\cdot P\cdot P^{-1}w    
$$

    
$$    
a' = X\cdot w    
$$
    
    

$$
a' = a
$$

Значит прогноз не изменится 

## Алгоритм преобразования

**Алгоритм:** 

1. Обучим модель на подготовелнных данных и вычислим R2.
2. Создадим обратимую матрицу.
3. Преобразуем признаки, умножив их на обратимую матрицу.
4. Обучим модель на преобразованных признаках и вычислим R2.
5. Сравним R2 исходной модели и преобразованной.

## Проверка алгоритма

Найдем значение `R2` для исходного датасета:

In [12]:
model_origin = LinearRegression()
model_origin.fit(train_features, train_target)
prediction_origin = model_origin.predict(test_features)

R2_score_origin = r2_score(test_target, prediction_origin)

print(f'R2_score исходного датасета: {R2_score_origin}')

R2_score исходного датасета: 0.43522757127026546


Создадим обратимую матрицу для кодирования:

In [13]:
#для умножения матриц необходимо, чтобы число столбцов первой матрицы совпадало с числом строк второй
invertible_matrix = np.random.randn(4, 4)
invertible_matrix

array([[ 6.75263588e-01,  7.91695456e-01, -1.26712631e-01,
        -6.53360913e-01],
       [ 8.80384258e-01, -1.57457923e-03, -1.45077554e+00,
         8.53387282e-01],
       [-3.52954773e-01, -4.87899694e-02,  4.41407091e-02,
        -6.22457539e-01],
       [-8.58916078e-01,  1.22762267e-01, -6.36315126e-01,
        -1.81933367e+00]])

In [18]:
inverse_matrix = np.linalg.inv(invertible_matrix)
inverse_matrix

array([[  0.88938319,   1.26482011,   8.10378039,  -2.49869833],
       [  0.13368836,  -1.62635341, -10.91673592,   2.92411919],
       [  0.24705726,  -0.27848737,   1.86256346,  -0.85660032],
       [ -0.49726992,  -0.60946678,  -5.2138912 ,   1.12690236]])

In [19]:
once_matrix = invertible_matrix @ inverse_matrix
once_matrix

array([[ 1.00000000e+00, -2.06689756e-16, -1.45549518e-15,
         6.45184665e-17],
       [ 7.56635038e-19,  1.00000000e+00, -8.64752642e-16,
         2.46839291e-16],
       [ 5.19428734e-17,  1.19525625e-16,  1.00000000e+00,
        -1.08501436e-16],
       [-2.01695331e-16,  1.36732529e-16, -2.93438938e-16,
         1.00000000e+00]])

Умножим признаки на обратимую матрицу:

In [15]:
train_features_update = train_features.values @ invertible_matrix
test_features_update = test_features.values @ invertible_matrix

Найдем значения `R2` для закодированного датасета:

In [16]:
model_update = LinearRegression()
model_update.fit(train_features_update, train_target)
prediction_update = model_update.predict(test_features_update)

R2_score_update = r2_score(test_target, prediction_update)

print(f'R2_score закодированного датасета: {R2_score_update}')

R2_score закодированного датасета: 0.435227571270403


In [17]:
print(f'R2_score исходного датасета: {R2_score_origin}')
print(f'R2_score закодированного датасета: {R2_score_update}')

R2_score исходного датасета: 0.43522757127026546
R2_score закодированного датасета: 0.435227571270403


## Вывод:

Получив датасет, мы провели разведывательный анализ данных, в ходе которых были найдены строки-дупликаты. Однако их наличие на качество выполнения задачи не может повлиять. Далее, начали подготовку данных: выделили целевой признак и произнаки для обучения моедли, разбили датасет на тренировочную и тестовую выборки. Качество модели мы оцениваем по R2. 

Основной целью проекта является доказательство того, что качество модели не изменится при преобразовании признаков. Для этого мы создали случайную обратимую матрицу (доказали, что она обратима). Умножив признаки на матрицу, мы преобразовали данные. Обучив модель на преобразованных данных вновь получили оценку R2. 

Сравнение оценок показало, что _при преобразовании исходного датасета качество моделей машинного обучения не ухудшилось._